package specs

import (
	"github.com/moov-io/iso8583"
	"github.com/moov-io/iso8583/encoding"
	"github.com/moov-io/iso8583/field"
	"github.com/moov-io/iso8583/padding"
	"github.com/moov-io/iso8583/prefix"
)

var Spec87Maestro *iso8583.MessageSpec = &iso8583.MessageSpec{
	Name: "ISO 8583 v1987 Hex",

	Fields: map[int]field.Field{
		0: field.NewString(&field.Spec{
			Length:      4,
			Description: "Message Type Indicator",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		1: field.NewBitmap(&field.Spec{
			Description: "Bitmap",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		2: field.NewString(&field.Spec{
			Length:      11,
			Description: "PAN",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.L,
		}),
		3: field.NewString(&field.Spec{
			Length:      6,
			Description: "Processing Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		4: field.NewString(&field.Spec{
			Length:      12,
			Description: "Amount, Transaction",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		5: field.NewString(&field.Spec{
			Length:      12,
			Description: "Amount, Settlement",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		6: field.NewString(&field.Spec{
			Length:      12,
			Description: "Amount, Cardholder Billing",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		7: field.NewString(&field.Spec{
			Length:      10,
			Description: "Transmission Date and Time",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		8: field.NewString(&field.Spec{
			Length:      8,
			Description: "Amount, Cardholder Billing Fee",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		9: field.NewString(&field.Spec{
			Length:      8,
			Description: "Conversion Rate, Settlement",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		10: field.NewString(&field.Spec{
			Length:      8,
			Description: "Conversion Rate, Cardholder Billing",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		11: field.NewString(&field.Spec{
			Length:      6,
			Description: "System Trace Audit Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		12: field.NewString(&field.Spec{
			Length:      6,
			Description: "Time, Local Transaction",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		13: field.NewString(&field.Spec{
			Length:      4,
			Description: "Date, Local Transaction",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		14: field.NewString(&field.Spec{
			Length:      4,
			Description: "Date, Expiration",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		15: field.NewString(&field.Spec{
			Length:      4,
			Description: "Date, Settlement",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		16: field.NewString(&field.Spec{
			Length:      4,
			Description: "Date, Conversion",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		17: field.NewString(&field.Spec{
			Length:      4,
			Description: "Date, Capture",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		18: field.NewString(&field.Spec{
			Length:      4,
			Description: "Merchant Type",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		19: field.NewString(&field.Spec{
			Length:      3,
			Description: "Acquiring Institution Country Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		20: field.NewString(&field.Spec{
			Length:      3,
			Description: "PAN Extended, Country Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		21: field.NewString(&field.Spec{
			Length:      3,
			Description: "Forwarding Institution Country Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		22: field.NewString(&field.Spec{
			Length:      3,
			Description: "Point-of-Service Entry Mode Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		23: field.NewString(&field.Spec{
			Length:      3,
			Description: "Card Sequence Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		24: field.NewString(&field.Spec{
			Length:      3,
			Description: "Network International Identifier",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		25: field.NewString(&field.Spec{
			Length:      2,
			Description: "POS Condition Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		26: field.NewString(&field.Spec{
			Length:      2,
			Description: "POS PIN Capture Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		27: field.NewString(&field.Spec{
			Length:      1,
			Description: "Authorization Identification Response Length",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		28: field.NewString(&field.Spec{
			Length:      9,
			Description: "Amount, Transaction Fee",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		29: field.NewString(&field.Spec{
			Length:      9,
			Description: "Amount, Settlement Fee",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		30: field.NewString(&field.Spec{
			Length:      9,
			Description: "Amount, Transaction Processing Fee",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		31: field.NewString(&field.Spec{
			Length:      9,
			Description: "Amount, Settlement Processing Fee",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		32: field.NewString(&field.Spec{
			Length:      11,
			Description: "Acquiring Institution Identification Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
			Pad:         padding.Left('0'),
		}),
		33: field.NewString(&field.Spec{
			Length:      11,
			Description: "Forwarding Institution Identification Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		34: field.NewString(&field.Spec{
			Length:      28,
			Description: "PAN, Extended",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		35: field.NewString(&field.Spec{
			Length:      37,
			Description: "Track 2 Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		36: field.NewString(&field.Spec{
			Length:      104,
			Description: "Track 3 Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		37: field.NewString(&field.Spec{
			Length:      12,
			Description: "Retrieval Reference Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		38: field.NewString(&field.Spec{
			Length:      6,
			Description: "Authorization Identification Response",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		39: field.NewString(&field.Spec{
			Length:      2,
			Description: "Response Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		40: field.NewString(&field.Spec{
			Length:      3,
			Description: "Service Restriction Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		41: field.NewString(&field.Spec{
			Length:      8,
			Description: "Card Acceptor Terminal Identification",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		42: field.NewString(&field.Spec{
			Length:      15,
			Description: "Card Acceptor Identification Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		43: field.NewString(&field.Spec{
			Length:      40,
			Description: "Card Acceptor Name/Location",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		44: field.NewString(&field.Spec{
			Length:      25,
			Description: "Additional Response Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		45: field.NewString(&field.Spec{
			Length:      76,
			Description: "Track 1 Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		46: field.NewString(&field.Spec{
			Length:      999,
			Description: "Expanded Additional Amounts",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		47: field.NewString(&field.Spec{
			Length:      999,
			Description: "Additional Data—National",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		48: field.NewString(&field.Spec{
			Length:      999,
			Description: "Additional Data—Private",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		49: field.NewString(&field.Spec{
			Length:      3,
			Description: "Currency Code, Transaction",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		50: field.NewString(&field.Spec{
			Length:      3,
			Description: "Currency Code, Settlement",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		51: field.NewString(&field.Spec{
			Length:      3,
			Description: "Currency Code, Cardholder Billing",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		52: field.NewString(&field.Spec{
			Length:      8,
			Description: "Personal Identification Number (PIN) Data",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		53: field.NewString(&field.Spec{
			Length:      16,
			Description: "Security-Related Control Information",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		54: field.NewString(&field.Spec{
			Length:      240,
			Description: "Additional Amounts",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		55: field.NewString(&field.Spec{
			Length:      999,
			Description: "Integrated Circuit Card (ICC) Related Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		56: field.NewString(&field.Spec{
			Length:      37,
			Description: "Payment Account Reference Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		57: field.NewString(&field.Spec{
			Length:      999,
			Description: "Reserved for National Use",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		58: field.NewString(&field.Spec{
			Length:      999,
			Description: "Authorizing Agent Institution ID",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		59: field.NewString(&field.Spec{
			Length:      999,
			Description: "Reserved for National Use",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		60: field.NewString(&field.Spec{
			Length:      999,
			Description: "Advice Reason Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		61: field.NewString(&field.Spec{
			Length:      999,
			Description: "Point of Service (POS) Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		62: field.NewString(&field.Spec{
			Length:      999,
			Description: "Intermediate Network Facility (INF) Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		63: field.NewString(&field.Spec{
			Length:      999,
			Description: "Network Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		64: field.NewString(&field.Spec{
			Length:      8,
			Description: "Message Authentication Code (MAC)",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		65: field.NewString(&field.Spec{
			Length:      8,
			Description: "Bit Map, Extended",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		66: field.NewString(&field.Spec{
			Length:      1,
			Description: "Settlement Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		67: field.NewString(&field.Spec{
			Length:      2,
			Description: "Extended Payment Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		68: field.NewString(&field.Spec{
			Length:      3,
			Description: "Receiving Institution Country Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		69: field.NewString(&field.Spec{
			Length:      3,
			Description: "Settlement Institution Country Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		70: field.NewString(&field.Spec{
			Length:      3,
			Description: "Network Management Information Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		71: field.NewString(&field.Spec{
			Length:      4,
			Description: "Message Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		72: field.NewString(&field.Spec{
			Length:      4,
			Description: "Message Number Last",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		73: field.NewString(&field.Spec{
			Length:      6,
			Description: "Date, Action",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		74: field.NewString(&field.Spec{
			Length:      10,
			Description: "Credits, Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		75: field.NewString(&field.Spec{
			Length:      10,
			Description: "Credits, Reversal Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		76: field.NewString(&field.Spec{
			Length:      10,
			Description: "Debits, Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		77: field.NewString(&field.Spec{
			Length:      10,
			Description: "Debits, Reversal Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		78: field.NewString(&field.Spec{
			Length:      10,
			Description: "Transfer, Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		79: field.NewString(&field.Spec{
			Length:      10,
			Description: "Transfer, Reversal Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		80: field.NewString(&field.Spec{
			Length:      10,
			Description: "Inquiries, Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		81: field.NewString(&field.Spec{
			Length:      10,
			Description: "Authorizations, Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		82: field.NewString(&field.Spec{
			Length:      12,
			Description: "Credits, Processing Fee Amount",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		83: field.NewString(&field.Spec{
			Length:      12,
			Description: "Credits, Transaction Fee Amount",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		84: field.NewString(&field.Spec{
			Length:      12,
			Description: "Debits, Processing Fee Amount",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		85: field.NewString(&field.Spec{
			Length:      12,
			Description: "Debits, Transaction Fee Amount",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		86: field.NewString(&field.Spec{
			Length:      16,
			Description: "Credits, Amount",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		87: field.NewString(&field.Spec{
			Length:      16,
			Description: "Credits, Reversal Amount",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		88: field.NewString(&field.Spec{
			Length:      16,
			Description: "Debits, Amount",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		89: field.NewString(&field.Spec{
			Length:      16,
			Description: "Debits, Reversal Amount",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		90: field.NewString(&field.Spec{
			Length:      42,
			Description: "Original Data Elements",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		91: field.NewString(&field.Spec{
			Length:      1,
			Description: "File Update Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		92: field.NewString(&field.Spec{
			Length:      2,
			Description: "File Security Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		93: field.NewString(&field.Spec{
			Length:      5,
			Description: "Response Indicator",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		94: field.NewString(&field.Spec{
			Length:      7,
			Description: "Service Indicator",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		95: field.NewString(&field.Spec{
			Length:      42,
			Description: "Replacement Amounts",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		96: field.NewString(&field.Spec{
			Length:      8,
			Description: "Message Security Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		97: field.NewString(&field.Spec{
			Length:      17,
			Description: "Amount, Net Settlement",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		98: field.NewString(&field.Spec{
			Length:      25,
			Description: "Payee",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		99: field.NewString(&field.Spec{
			Length:      11,
			Description: "Settlement Institution Identification Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		100: field.NewString(&field.Spec{
			Length:      11,
			Description: "Receiving Institution Identification Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		101: field.NewString(&field.Spec{
			Length:      17,
			Description: "File Name",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		102: field.NewString(&field.Spec{
			Length:      28,
			Description: "Account Identification 1",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		103: field.NewString(&field.Spec{
			Length:      28,
			Description: "Account Identification 2",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		104: field.NewString(&field.Spec{
			Length:      999,
			Description: "Digital Payment Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		105: field.NewString(&field.Spec{
			Length:      999,
			Description: "Enhanced Identification Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		106: field.NewString(&field.Spec{
			Length:      999,
			Description: "Private Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		107: field.NewString(&field.Spec{
			Length:      999,
			Description: "India On-Soil Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		108: field.NewString(&field.Spec{
			Length:      999,
			Description: "Additional Transaction Reference Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		109: field.NewString(&field.Spec{
			Length:      999,
			Description: "Reserved for ISO Use",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		110: field.NewString(&field.Spec{
			Length:      999,
			Description: "Additional Data-2",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		111: field.NewString(&field.Spec{
			Length:      999,
			Description: "Amount, Currency Conversion Assessment",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		112: field.NewString(&field.Spec{
			Length:      999,
			Description: "Additional Data (National Use)",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		113: field.NewString(&field.Spec{
			Length:      999,
			Description: "Reserved for National Use",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		114: field.NewString(&field.Spec{
			Length:      999,
			Description: "Reserved for National Use",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		115: field.NewString(&field.Spec{
			Length:      999,
			Description: "Reserved for National Use",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		116: field.NewString(&field.Spec{
			Length:      999,
			Description: "Reserved for National Use",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		117: field.NewString(&field.Spec{
			Length:      999,
			Description: "Reserved for National Use",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		118: field.NewString(&field.Spec{
			Length:      999,
			Description: "Reserved for National Use",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		119: field.NewString(&field.Spec{
			Length:      999,
			Description: "Reserved for National Use",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		120: field.NewString(&field.Spec{
			Length:      999,
			Description: "Record Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		121: field.NewString(&field.Spec{
			Length:      999,
			Description: "Authorizing Agent Identification Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		122: field.NewString(&field.Spec{
			Length:      100,
			Description: "Additional Record Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		123: field.NewString(&field.Spec{
			Length:      999,
			Description: "Mastercard Merchant Data Services",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		124: field.NewString(&field.Spec{
			Length:      299,
			Description: "Member-Defined Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		125: field.NewString(&field.Spec{
			Length:      8,
			Description: "New PIN Data",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		126: field.NewString(&field.Spec{
			Length:      50,
			Description: "Switch Private Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		127: field.NewString(&field.Spec{
			Length:      100,
			Description: "Processor Private Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LLL,
		}),
		128: field.NewString(&field.Spec{
			Length:      8,
			Description: "Message Authentication Code (MAC)",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
	},
}
