package specs

import (
	"github.com/moov-io/iso8583"
	"github.com/moov-io/iso8583/encoding"
	"github.com/moov-io/iso8583/field"
	"github.com/moov-io/iso8583/padding"
	"github.com/moov-io/iso8583/prefix"
)

var Spec87Visa *iso8583.MessageSpec = &iso8583.MessageSpec{
	Name: "ISO 8583 v1987 Hex",

	Fields: map[int]field.Field{
		0: field.NewString(&field.Spec{
			Length:      4,
			Description: "Message Type Indicator",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		1: field.NewBitmap(&field.Spec{
			Description: "Bitmap",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		2: field.NewString(&field.Spec{
			Length:      11,
			Description: "PAN",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		3: field.NewString(&field.Spec{
			Length:      6,
			Description: "Processing Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		4: field.NewString(&field.Spec{
			Length:      12,
			Description: "Amount, Transaction",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		5: field.NewString(&field.Spec{
			Length:      12,
			Description: "Amount, Settlement",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		6: field.NewString(&field.Spec{
			Length:      12,
			Description: "Amount, Cardholder Billing",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		7: field.NewString(&field.Spec{
			Length:      10,
			Description: "Transmission Date and Time",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		8: field.NewString(&field.Spec{
			Length:      8,
			Description: "Amount, Cardholder Billing Fee",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		9: field.NewString(&field.Spec{
			Length:      8,
			Description: "Conversion Rate, Settlement",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		10: field.NewString(&field.Spec{
			Length:      8,
			Description: "Conversion Rate, Cardholder Billing",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		11: field.NewString(&field.Spec{
			Length:      6,
			Description: "System Trace Audit Number",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		12: field.NewString(&field.Spec{
			Length:      6,
			Description: "Time, Local Transaction",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		13: field.NewString(&field.Spec{
			Length:      4,
			Description: "Date, Local Transaction",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		14: field.NewString(&field.Spec{
			Length:      4,
			Description: "Date, Expiration",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		15: field.NewString(&field.Spec{
			Length:      4,
			Description: "Date, Settlement",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		16: field.NewString(&field.Spec{
			Length:      4,
			Description: "Date, Conversion",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		17: field.NewString(&field.Spec{
			Length:      4,
			Description: "Date, Capture",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		18: field.NewString(&field.Spec{
			Length:      4,
			Description: "Merchant Type",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		19: field.NewString(&field.Spec{
			Length:      3,
			Description: "Acquiring Institution Country Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
			Pad:         padding.Left('0'),
		}),
		20: field.NewString(&field.Spec{
			Length:      3,
			Description: "PAN Extended, Country Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
			Pad:         padding.Left('0'),
		}),
		22: field.NewString(&field.Spec{
			Length:      4,
			Description: "Point-of-Service Entry Mode Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		23: field.NewString(&field.Spec{
			Length:      4,
			Description: "Card Sequence Number",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		24: field.NewString(&field.Spec{
			Length:      4,
			Description: "Network International Identifier",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
			Pad:         padding.Left('0'),
		}),
		25: field.NewString(&field.Spec{
			Length:      2,
			Description: "POS Condition Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		26: field.NewString(&field.Spec{
			Length:      2,
			Description: "POS PIN Capture Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		28: field.NewString(&field.Spec{
			Length:      9,
			Description: "Amount, Transaction Fee",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		32: field.NewString(&field.Spec{
			Length:      11,
			Description: "Acquiring Institution Identification Code",
			Enc:         encoding.BCD,
			Pref:        prefix.Binary.L,
			Pad:         padding.Left('0'),
		}),
		33: field.NewString(&field.Spec{
			Length:      11,
			Description: "Forwarding Institution Identification Code",
			Enc:         encoding.BCD,
			Pref:        prefix.Binary.L,
			Pad:         padding.Left('0'),
		}),
		34: field.NewString(&field.Spec{
			Length:      15,
			Description: "PAN, Extended",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		35: field.NewString(&field.Spec{
			Length:      20,
			Description: "Track 2 Data",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		36: field.NewString(&field.Spec{
			Length:      53,
			Description: "Track 3 Data",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		37: field.NewString(&field.Spec{
			Length:      12,
			Description: "Retrieval Reference Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		38: field.NewString(&field.Spec{
			Length:      6,
			Description: "Authorization Identification Response",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		39: field.NewString(&field.Spec{
			Length:      2,
			Description: "Response Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		41: field.NewString(&field.Spec{
			Length:      8,
			Description: "Card Acceptor Terminal Identification",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		42: field.NewString(&field.Spec{
			Length:      15,
			Description: "Card Acceptor Identification Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		43: field.NewString(&field.Spec{
			Length:      40,
			Description: "Card Acceptor Name/Location",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		44: field.NewString(&field.Spec{
			Length:      26,
			Description: "Additional Response Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		45: field.NewString(&field.Spec{
			Length:      77,
			Description: "Track 1 Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		46: field.NewString(&field.Spec{
			Length:      256,
			Description: "Amounts, Fees",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		47: field.NewString(&field.Spec{
			Length:      256,
			Description: "Additional Data—National",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		48: field.NewString(&field.Spec{
			Length:      256,
			Description: "Additional Data—Private",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		49: field.NewString(&field.Spec{
			Length:      3,
			Description: "Currency Code, Transaction",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
			Pad:         padding.Left('0'),
		}),
		50: field.NewString(&field.Spec{
			Length:      3,
			Description: "Currency Code, Settlement",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
			Pad:         padding.Left('0'),
		}),
		51: field.NewString(&field.Spec{
			Length:      3,
			Description: "Currency Code, Cardholder Billing",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
			Pad:         padding.Left('0'),
		}),
		52: field.NewString(&field.Spec{
			Length:      8,
			Description: "Personal Identification Number (PIN) Data",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		53: field.NewString(&field.Spec{
			Length:      16,
			Description: "Security-Related Control Information",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		54: field.NewString(&field.Spec{
			Length:      121,
			Description: "Additional Amounts",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		55: field.NewString(&field.Spec{
			Length:      256,
			Description: "Integrated Circuit Card (ICC) Related Data",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		56: field.NewString(&field.Spec{
			Length:      256,
			Description: "Payment Account Reference Data",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		57: field.NewString(&field.Spec{
			Length:      256,
			Description: "Reserved Nationa",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		58: field.NewString(&field.Spec{
			Length:      256,
			Description: "Reserved National",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		59: field.NewString(&field.Spec{
			Length:      15,
			Description: "National Point-of-Service Geographic Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		60: field.NewString(&field.Spec{
			Length:      6,
			Description: "Additional POS Information",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		61: field.NewString(&field.Spec{
			Length:      19,
			Description: "Other Amounts",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		62: field.NewString(&field.Spec{
			Length:      256,
			Description: "Custom Payment Service Fields Bitmap",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		63: field.NewString(&field.Spec{
			Length:      256,
			Description: "SMS Private-Use Fields",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		66: field.NewString(&field.Spec{
			Length:      1,
			Description: "Settlement Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
			Pad:         padding.Left('0'),
		}),
		67: field.NewString(&field.Spec{
			Length:      2,
			Description: "Extended Payment Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		68: field.NewString(&field.Spec{
			Length:      3,
			Description: "Receiving Institution Country Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
			Pad:         padding.Left('0'),
		}),
		69: field.NewString(&field.Spec{
			Length:      3,
			Description: "Settlement Institution Country Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
			Pad:         padding.Left('0'),
		}),
		70: field.NewString(&field.Spec{
			Length:      3,
			Description: "Network Management Information Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
			Pad:         padding.Left('0'),
		}),
		71: field.NewString(&field.Spec{
			Length:      4,
			Description: "Message Number",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		72: field.NewString(&field.Spec{
			Length:      4,
			Description: "Message Number Last",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		73: field.NewString(&field.Spec{
			Length:      6,
			Description: "Date, Action",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		74: field.NewString(&field.Spec{
			Length:      10,
			Description: "Credits, Number",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		75: field.NewString(&field.Spec{
			Length:      10,
			Description: "Credits, Reversal Number",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		76: field.NewString(&field.Spec{
			Length:      10,
			Description: "Debits, Number",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		77: field.NewString(&field.Spec{
			Length:      10,
			Description: "Debits, Reversal Number",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		78: field.NewString(&field.Spec{
			Length:      10,
			Description: "Transfer, Number",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		79: field.NewString(&field.Spec{
			Length:      10,
			Description: "Transfer, Reversal Number",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		80: field.NewString(&field.Spec{
			Length:      10,
			Description: "Inquiries, Number",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		81: field.NewString(&field.Spec{
			Length:      10,
			Description: "Authorizations, Number",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		82: field.NewString(&field.Spec{
			Length:      12,
			Description: "Credits, Processing Fee Amount",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		83: field.NewString(&field.Spec{
			Length:      12,
			Description: "Credits, Transaction Fee Amount",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		84: field.NewString(&field.Spec{
			Length:      12,
			Description: "Debits, Processing Fee Amount",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		85: field.NewString(&field.Spec{
			Length:      12,
			Description: "Debits, Transaction Fee Amount",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		86: field.NewString(&field.Spec{
			Length:      16,
			Description: "Credits, Amount",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		87: field.NewString(&field.Spec{
			Length:      16,
			Description: "Credits, Reversal Amount",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		88: field.NewString(&field.Spec{
			Length:      16,
			Description: "Debits, Amount",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		89: field.NewString(&field.Spec{
			Length:      16,
			Description: "Debits, Reversal Amount",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		90: field.NewString(&field.Spec{
			Length:      42,
			Description: "Original Data Elements",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		91: field.NewString(&field.Spec{
			Length:      1,
			Description: "File Update Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		92: field.NewString(&field.Spec{
			Length:      2,
			Description: "File Security Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		94: field.NewString(&field.Spec{
			Length:      7,
			Description: "Service Indicator",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		95: field.NewString(&field.Spec{
			Length:      42,
			Description: "Replacement Amounts",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		96: field.NewString(&field.Spec{
			Length:      64,
			Description: "Message Security Code",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		97: field.NewString(&field.Spec{
			Length:      17,
			Description: "Amount, Net Settlement",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		98: field.NewString(&field.Spec{
			Length:      25,
			Description: "Payee",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		99: field.NewString(&field.Spec{
			Length:      7,
			Description: "Settlement Institution Identification Code",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		100: field.NewString(&field.Spec{
			Length:      7,
			Description: "Receiving Institution Identification Code",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		101: field.NewString(&field.Spec{
			Length:      18,
			Description: "File Name",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		102: field.NewString(&field.Spec{
			Length:      29,
			Description: "Account Identification 1",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		103: field.NewString(&field.Spec{
			Length:      29,
			Description: "Account Identification 2",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		104: field.NewString(&field.Spec{
			Length:      256,
			Description: "Transaction Description",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		105: field.NewString(&field.Spec{
			Length:      128,
			Description: "Double-Length DES Key (Triple DES)",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		106: field.NewString(&field.Spec{
			Length:      256,
			Description: "Reserved ISO",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		107: field.NewString(&field.Spec{
			Length:      256,
			Description: "Reserved ISO",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		108: field.NewString(&field.Spec{
			Length:      256,
			Description: "Reserved ISO",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		109: field.NewString(&field.Spec{
			Length:      256,
			Description: "Reserved ISO",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		110: field.NewString(&field.Spec{
			Length:      256,
			Description: "Reserved ISO",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		111: field.NewString(&field.Spec{
			Length:      256,
			Description: "Reserved ISO",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		112: field.NewString(&field.Spec{
			Length:      256,
			Description: "Reserved National",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		113: field.NewString(&field.Spec{
			Length:      256,
			Description: "Reserved National",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		114: field.NewString(&field.Spec{
			Length:      256,
			Description: "Reserved National",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		115: field.NewString(&field.Spec{
			Length:      25,
			Description: "Additional Trace Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		116: field.NewString(&field.Spec{
			Length:      256,
			Description: "Card Issuer Reference Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		117: field.NewString(&field.Spec{
			Length:      256,
			Description: "National Use",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		118: field.NewString(&field.Spec{
			Length:      256,
			Description: "Intra-Country Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		119: field.NewString(&field.Spec{
			Length:      256,
			Description: "Settlement Service Data (International Only)",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		120: field.NewString(&field.Spec{
			Length:      65537,
			Description: "Auxiliary Transaction Data (TLV Format)",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.LL,
		}),
		121: field.NewString(&field.Spec{
			Length:      12,
			Description: "Issuing Institution Identification Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		123: field.NewString(&field.Spec{
			Length:      256,
			Description: "Verification Data",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		125: field.NewString(&field.Spec{
			Length:      256,
			Description: "Supporting Information",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.Binary.L,
		}),
		126: field.NewString(&field.Spec{
			Length:      256,
			Description: "Visa Private-Use Fields",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		127: field.NewString(&field.Spec{
			Length:      256,
			Description: "File Maintenance",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		128: field.NewString(&field.Spec{
			Length:      8,
			Description: "Message Authentication Code",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		130: field.NewString(&field.Spec{
			Length:      3,
			Description: "Terminal Capability Profile",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		131: field.NewString(&field.Spec{
			Length:      5,
			Description: "Terminal Verification Results (TVR)",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		132: field.NewString(&field.Spec{
			Length:      4,
			Description: "Unpredictable Number",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		133: field.NewString(&field.Spec{
			Length:      8,
			Description: "Reserved for future use",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		134: field.NewString(&field.Spec{
			Length:      33,
			Description: "Visa Discretionary Data, Usage 1/2",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		135: field.NewString(&field.Spec{
			Length:      16,
			Description: "Issuer Discretionary Data",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		136: field.NewString(&field.Spec{
			Length:      8,
			Description: "Cryptogram",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		137: field.NewString(&field.Spec{
			Length:      2,
			Description: "Application Transaction Counter",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		138: field.NewString(&field.Spec{
			Length:      2,
			Description: "Application Interchange Profil",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		139: field.NewString(&field.Spec{
			Length:      10,
			Description: "ARPC Response Cryptogram and Code",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.Fixed,
		}),
		140: field.NewString(&field.Spec{
			Length:      17,
			Description: "Issuer Authentication Data",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		142: field.NewString(&field.Spec{
			Length:      256,
			Description: "Issuer Script",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		143: field.NewString(&field.Spec{
			Length:      21,
			Description: "Issuer Script Results",
			Enc:         encoding.Binary,
			Pref:        prefix.Binary.L,
		}),
		144: field.NewString(&field.Spec{
			Length:      2,
			Description: "Cryptogram Transaction Type",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		145: field.NewString(&field.Spec{
			Length:      3,
			Description: "Terminal Country Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
			Pad:         padding.Left('0'),
		}),
		146: field.NewString(&field.Spec{
			Length:      6,
			Description: "Terminal Transaction Date",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		147: field.NewString(&field.Spec{
			Length:      12,
			Description: "Cryptogram Amount",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
		148: field.NewString(&field.Spec{
			Length:      3,
			Description: "Cryptogram Currency Code",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
			Pad:         padding.Left('0'),
		}),
		149: field.NewString(&field.Spec{
			Length:      12,
			Description: "Cryptogram Cashback Amount",
			Enc:         encoding.BCD,
			Pref:        prefix.BCD.Fixed,
		}),
	},
}
