package specs

import (
	"github.com/moov-io/iso8583/encoding"
	"github.com/moov-io/iso8583/field"
	"github.com/moov-io/iso8583/mastercard/field48"
	"github.com/moov-io/iso8583/prefix"
)

var Spec87MCField48 *field48.Field48Spec = &field48.Field48Spec{
	Name: "ISO 8583 v1987 Mastercard Field 48",

	Fields: map[int]field.Field{
		1: field.NewString(&field.Spec{
			Length:      1,
			Description: "TCC",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.Fixed,
		}),
		11: field.NewString(&field.Spec{
			Length:      70,
			Description: "Key Exchange Data Block",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		17: field.NewString(&field.Spec{
			Length:      1,
			Description: "Authentication Indicator",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		19: field.NewString(&field.Spec{
			Length:      23,
			Description: "Fraud Notification Information",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		21: field.NewString(&field.Spec{
			Length:      11,
			Description: "Acceptance Data (Single Message)",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		22: field.NewString(&field.Spec{
			Length:      21,
			Description: "Multi-Purpose Merchant Indicatorn",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		23: field.NewString(&field.Spec{
			Length:      2,
			Description: "Payment Initiation Channel",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		25: field.NewString(&field.Spec{
			Length:      14,
			Description: "Mastercard Cash Program Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		26: field.NewString(&field.Spec{
			Length:      3,
			Description: "Wallet Program Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		27: field.NewString(&field.Spec{
			Length:      97,
			Description: "Transaction Analysis",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		28: field.NewString(&field.Spec{
			Length:      10,
			Description: "Cardless ATM Order ID",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		29: field.NewString(&field.Spec{
			Length:      1,
			Description: "Additional POS Terminal Locations",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		30: field.NewString(&field.Spec{
			Length:      64,
			Description: "Token Transaction Identifier",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		32: field.NewString(&field.Spec{
			Length:      6,
			Description: "Mastercard Assigned ID",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		33: field.NewString(&field.Spec{
			Length:      36,
			Description: "PAN Mapping File Information",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		34: field.NewString(&field.Spec{
			Length:      11,
			Description: "Dynamic CVC 3 Application Transaction Counter (ATC) Information",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		35: field.NewString(&field.Spec{
			Length:      1,
			Description: "Contactless Device Request Response",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		37: field.NewString(&field.Spec{
			Length:      56,
			Description: "Additional Merchant Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		38: field.NewString(&field.Spec{
			Length:      1,
			Description: "Account Category",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		39: field.NewString(&field.Spec{
			Length:      30,
			Description: "Account Data Compromise Information",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		40: field.NewString(&field.Spec{
			Length:      40,
			Description: "Electronic Commerce Merchant/Cardholder Certificate Serial Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		41: field.NewString(&field.Spec{
			Length:      95,
			Description: "Electronic Commerce Certificate Qualifying Information",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		42: field.NewString(&field.Spec{
			Length:      7,
			Description: "Electronic Commerce Indicators",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		43: field.NewString(&field.Spec{
			Length:      32,
			Description: "Universal Cardholder Authentication Field (UCAF)",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		48: field.NewString(&field.Spec{
			Length:      73,
			Description: "Mobile Program Indicators",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		49: field.NewString(&field.Spec{
			Length:      15,
			Description: "Time Validation Information",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		52: field.NewString(&field.Spec{
			Length:      2,
			Description: "Transaction Integrity Class",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		54: field.NewString(&field.Spec{
			Length:      84,
			Description: "Ancillary Service Charges",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		56: field.NewString(&field.Spec{
			Length:      99,
			Description: "Security Services Additional Data for Issuers",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		59: field.NewString(&field.Spec{
			Length:      9,
			Description: "Original Switch Serial Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		61: field.NewString(&field.Spec{
			Length:      5,
			Description: "POS Data, Extended Condition Codes",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		63: field.NewString(&field.Spec{
			Length:      15,
			Description: "Trace ID",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		64: field.NewString(&field.Spec{
			Length:      4,
			Description: "Transit Program",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		65: field.NewString(&field.Spec{
			Length:      2,
			Description: "Terminal Compliant Indicator",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		66: field.NewString(&field.Spec{
			Length:      45,
			Description: "Authentication Data",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		67: field.NewString(&field.Spec{
			Length:      99,
			Description: "MoneySend Information",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		69: field.NewString(&field.Spec{
			Length:      99,
			Description: "Trace ID of Authorization Advice",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		70: field.NewString(&field.Spec{
			Length:      5,
			Description: "Implied Decimal",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		71: field.NewString(&field.Spec{
			Length:      40,
			Description: "On-behalf Service (OBS)",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		72: field.NewString(&field.Spec{
			Length:      16,
			Description: "Issuer Chip Authentication",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		74: field.NewString(&field.Spec{
			Length:      30,
			Description: "Additional Processing Information",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		75: field.NewString(&field.Spec{
			Length:      32,
			Description: "Fraud Assessment Prediction Information",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		76: field.NewString(&field.Spec{
			Length:      1,
			Description: "Mastercard Electronic Transaction Indicator",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		77: field.NewString(&field.Spec{
			Length:      3,
			Description: "Transaction Type Identifier",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		79: field.NewString(&field.Spec{
			Length:      50,
			Description: "Chip CVR/TVR Bit Error Results Listing",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		80: field.NewString(&field.Spec{
			Length:      2,
			Description: "PIN Service Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		81: field.NewString(&field.Spec{
			Length:      1,
			Description: "Maestro PIN-less Program Indicator",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		82: field.NewString(&field.Spec{
			Length:      2,
			Description: "Address Verification Service Request",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		83: field.NewString(&field.Spec{
			Length:      1,
			Description: "Address Verification Service Response",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		84: field.NewString(&field.Spec{
			Length:      2,
			Description: "Merchant Advice Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		87: field.NewString(&field.Spec{
			Length:      1,
			Description: "Card Validation Code Result",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		88: field.NewString(&field.Spec{
			Length:      1,
			Description: "Magnetic Stripe Compliance Status Indicator",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		89: field.NewString(&field.Spec{
			Length:      1,
			Description: "Magnetic Stripe Compliance Error Indicator",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		90: field.NewString(&field.Spec{
			Length:      1,
			Description: "Lodging and Auto Rental Indicator",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		92: field.NewString(&field.Spec{
			Length:      3,
			Description: "CVC 2 Value",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		93: field.NewString(&field.Spec{
			Length:      15,
			Description: "Airline Ticket Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		94: field.NewString(&field.Spec{
			Length:      28,
			Description: "Program Participation Indicator",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		95: field.NewString(&field.Spec{
			Length:      1,
			Description: "Mastercard Promotion Code",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		98: field.NewString(&field.Spec{
			Length:      6,
			Description: "Mastercard Corporate Fleet Card ID/Driver Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
		99: field.NewString(&field.Spec{
			Length:      15,
			Description: "Mastercard Corporate Fleet Card Vehicle Number",
			Enc:         encoding.EBCDIC,
			Pref:        prefix.EBCDIC.LL,
		}),
	},
}
